---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, detaching, snapmanager, features, disks, aggregates, features, svm 
summary: Les limitations connues indiquent les plateformes, les appareils ou les fonctions non pris en charge par cette version du produit, ou qui ne fonctionnent pas correctement avec celle-ci. Examinez attentivement ces limitations. 
---
= Limitations connues de Cloud Volumes ONTAP chez tous les fournisseurs de cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les limitations connues indiquent les plateformes, les appareils ou les fonctions non pris en charge par cette version du produit, ou qui ne fonctionnent pas correctement avec celle-ci. Examinez attentivement ces limitations.

Les limitations suivantes s'appliquent à Cloud Volumes ONTAP chez tous les fournisseurs de cloud : AWS, Azure et Google Cloud.



== Fonctionnalités ONTAP non prises en charge

Les fonctionnalités suivantes ne sont pas prises en charge avec Cloud Volumes ONTAP :

* Déduplication en ligne au niveau de l’agrégat
* Déduplication en arrière-plan au niveau de l'agrégat
* Centre de maintenance des disques
* Assainissement des disques
* Mise en miroir FabricPool
* Fibre Channel (FC)
* Flash Pools
* Volumes infinis
* Groupes d'interface
* Basculement LIF intranode
* MetroCluster
* Vérification multi-administrateurs
+
L'activation de la vérification multi-administrateur sur Cloud Volumes ONTAP entraînera une configuration non prise en charge.

* RAID4, RAID-DP, RAID-TEC (RAID0 est pris en charge)
* Processeur de service
* SnapLock Compliance et modes Enterprise (seul Cloud WORM est pris en charge)
* SnapMirror Synchronous
* VLAN
* Disponibilité continue (CA) SMB
+
https://kb.netapp.com/on-prem/ontap/da/NAS/NAS-KBs/What_are_SMB_Continuous_Availability_CA_Shares["Partages SMB disponibles en permanence"^] pour les opérations non perturbatrices ne sont pas prises en charge.





== Opérations de réplication simultanées maximales

Le nombre maximal de transferts simultanés SnapMirror ou SnapVault pour Cloud Volumes ONTAP est de 100 par nœud, quel que soit le type d'instance ou le type de machine.



== Les instantanés du fournisseur de cloud ne doivent pas être utilisés pour vos plans de sauvegarde et de restauration

Il est déconseillé d'utiliser les snapshots de votre fournisseur de cloud dans le cadre de votre plan de sauvegarde et de restauration pour les données Cloud Volumes ONTAP. Vous devez toujours utiliser les copies Snapshot ONTAP ou des solutions de sauvegarde tierces pour sauvegarder et restaurer les données hébergées sur Cloud Volumes ONTAP.

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-backup-to-cloud.html["Apprenez à utiliser NetApp Backup and Recovery pour sauvegarder et restaurer les données ONTAP"^].


NOTE: Les points de cohérence ONTAP dans le système de fichiers WAFL déterminent la cohérence des données. Seul ONTAP peut mettre au repos le système de fichiers WAFL pour effectuer une sauvegarde cohérente après panne.



== Cloud Volumes ONTAP prend uniquement en charge les instances de VM réservées et à la demande

Cloud Volumes ONTAP peut s'exécuter sur une instance de machine virtuelle réservée ou à la demande de votre fournisseur de cloud. Les autres types d'instances de machine virtuelle ne sont pas pris en charge.



== Les solutions de gestion automatique des ressources applicatives ne doivent pas être utilisées

Les solutions de gestion automatique des ressources applicatives ne doivent pas gérer les systèmes Cloud Volumes ONTAP. Cela peut entraîner une modification vers une configuration non prise en charge. Par exemple, la solution pourrait changer Cloud Volumes ONTAP en un type d’instance de machine virtuelle non pris en charge.



== Les mises à jour logicielles doivent être effectuées par NetApp Console

Les mises à niveau de Cloud Volumes ONTAP doivent être effectuées depuis la NetApp Console. Vous ne devez pas mettre à niveau Cloud Volumes ONTAP en utilisant System Manager ou la CLI. Cela peut avoir un impact sur la stabilité du système.



== Le déploiement de Cloud Volumes ONTAP ne doit pas être modifié depuis la console de votre fournisseur de cloud

Les modifications apportées à la configuration Cloud Volumes ONTAP depuis la console de votre fournisseur de cloud entraînent une configuration non prise en charge. Toute modification des ressources Cloud Volumes ONTAP créées et gérées par la Console peut impacter la stabilité du système et la capacité de la Console à gérer le système.


NOTE: Après le déploiement initial, la modification du nom de l'abonnement Azure utilisé pour les ressources Cloud Volumes ONTAP est prise en charge.



== Les disques et les agrégats doivent être gérés depuis la Console

Tous les disques et agrégats doivent être créés et supprimés directement depuis la Console. Vous ne devez pas effectuer ces actions depuis un autre outil de gestion. Le faire peut nuire à la stabilité du système, entraver la possibilité d'ajouter des disques à l'avenir et potentiellement générer des frais redondants de fournisseur de cloud.



== Limitation de licence SnapManager

SnapManager par serveur sont prises en charge avec Cloud Volumes ONTAP. Les licences par système de stockage (SnapManager suite) ne sont pas prises en charge.



== Limitations liées aux agents et extensions tiers

Les agents tiers et les extensions de machine virtuelle ne sont pas pris en charge sur les instances de machine virtuelle Cloud Volumes ONTAP.
